name = "PkgMassInstaller"
uuid = "25937451-55af-4cf1-a681-2354f35bf0f3"
authors = ["josePereiro <jose.pereiro.lab@gmail.com> and contributors"]
version = "0.3.1"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
